// services/project.service.ts
import { Injectable } from '@angular/core';

export interface IProject {
  id: number;
  title: string;
  description: string;
  longDescription?: string;
  technologies: string[];
  category: 'academique' | 'auto-formation' | 'professionnel' | 'freelance';
  image: string;
  screenshots?: string[];
  demoUrl?: string;
  githubUrl?: string;
  year: number;
  client?: string;
  duration?: string;
  team?: string;
  challenges?: string[];
  features?: string[];
}

@Injectable({
  providedIn: 'root',
})
export class ProjectService {
  private projects: IProject[] = [
    {
      id: 1,
      title: 'Mur Mur',
      description: '',
      longDescription: '',
      technologies: [
        'Next js',
        'Node.js',
        'Docker',
        'Express js',
        'MongoDB Atlass',
        'Tailwind',
        'TypeScript',
      ],
      category: 'professionnel',
      image: 'assets/projects/murmur/murmur.png',
      screenshots: [
        'assets/projects/murmur/devis/devis1.png',
        'assets/projects/murmur/devis/devis2.png',
        'assets/projects/murmur/devis/devis3.png',
        'assets/projects/murmur/devis/devis4.png',
        'assets/projects/murmur/devis/devis5.png',
        'assets/projects/murmur/devis/devis6.png',
        'assets/projects/murmur/devis/devis7.png',
        'assets/projects/murmur/devis/devis8.png',
        'assets/projects/murmur/devis/devis9.png',
        'assets/projects/murmur/devis/devis10.png',
        'assets/projects/murmur/devis/devis11.png',
        'assets/projects/murmur/admin/admin1.png',
        'assets/projects/murmur/admin/admin2.png',
        'assets/projects/murmur/admin/admin3.png',
        'assets/projects/murmur/admin/admin4.png',
        'assets/projects/murmur/admin/admin5.png',
        'assets/projects/murmur/admin/admin6.png',
        'assets/projects/murmur/admin/admin7.png',
        'assets/projects/murmur/admin/admin8.png',
        'assets/projects/murmur/admin/admin9.png',
        'assets/projects/murmur/admin/admin10.png',
        'assets/projects/murmur/admin/admin11.png',
        'assets/projects/murmur/admin/admin12.png',
        'assets/projects/murmur/admin/admin13.png',
        'assets/projects/murmur/admin/admin14.png',
        'assets/projects/murmur/admin/admin15.png',
        'assets/projects/murmur/admin/admin16.png',
        'assets/projects/murmur/admin/admin17.png',
        'assets/projects/murmur/client/client1.png',
        'assets/projects/murmur/client/client2.png',
        'assets/projects/murmur/client/client3.png',
        'assets/projects/murmur/client/client4.png',
        'assets/projects/murmur/client/client5.png',
        'assets/projects/murmur/client/client6.png',
        'assets/projects/murmur/client/client7.png',
        'assets/projects/murmur/client/client8.png',
        'assets/projects/murmur/client/client9.png',
        'assets/projects/murmur/client/client10.png',
        'assets/projects/murmur/client/client11.png',
        'assets/projects/murmur/client/client12.png',
        'assets/projects/murmur/client/client13.png',
        'assets/projects/murmur/client/client14.png',
        'assets/projects/murmur/client/client15.png',
        'assets/projects/murmur/seo/seo1.png',
        'assets/projects/murmur/seo/seo2.png',
        'assets/projects/murmur/seo/seo3.png',
        'assets/projects/murmur/seo/seo4.png',
        'assets/projects/murmur/seo/seo5.png',
        'assets/projects/murmur/seo/seo6.png',
        'assets/projects/murmur/seo/seo7.png',
        'assets/projects/murmur/seo/seo8.png',
        'assets/projects/murmur/seo/seo9.png',
        'assets/projects/murmur/seo/seo10.png',
        'assets/projects/murmur/seo/seo11.png',
        'assets/projects/murmur/seo/seo12.png',
        'assets/projects/murmur/seo/seo13.png',
        'assets/projects/murmur/seo/seo14.png',
        'assets/projects/murmur/seo/seo15.png',
        'assets/projects/murmur/seo/seo16.png',
        'assets/projects/murmur/seo/seo17.png',
        'assets/projects/murmur/seo/seo18.png',
      ],
      demoUrl: 'https://www.mur-mur.fr/',
      githubUrl: 'https://github.com/votre-projet/ecommerce',
      year: 2024,
      client: 'Mur Mur',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 2,
      title: 'Open Mur',
      description: '',
      longDescription: '',
      technologies: [
        'Next js',
        'Node.js',
        'Docker',
        'Express js',
        'MongoDB Atlass',
        'Tailwind',
        'TypeScript',
      ],
      category: 'professionnel',
      image: 'assets/projects/openmur/openmur.webp',
      screenshots: [
        'assets/projects/openmur/devis/devis1.webp',
        'assets/projects/openmur/devis/devis2.webp',
        'assets/projects/openmur/devis/devis3.webp',
        'assets/projects/openmur/admin/admin1.webp',
        'assets/projects/openmur/admin/admin2.webp',
        'assets/projects/openmur/admin/admin3.webp',
        'assets/projects/openmur/admin/admin4.webp',
        'assets/projects/openmur/admin/admin5.webp',
        'assets/projects/openmur/admin/admin6.webp',
        'assets/projects/openmur/admin/admin7.webp',
        'assets/projects/openmur/admin/admin8.webp',
        'assets/projects/openmur/admin/admin9.webp',
        'assets/projects/openmur/admin/admin10.webp',
        'assets/projects/openmur/admin/admin11.webp',
        'assets/projects/openmur/admin/admin12.webp',
        'assets/projects/openmur/admin/admin13.webp',
        'assets/projects/openmur/admin/admin14.webp',
        'assets/projects/openmur/admin/admin15.webp',
        'assets/projects/openmur/admin/admin16.webp',
        'assets/projects/openmur/admin/admin17.webp',
        'assets/projects/openmur/client/client1.webp',
        'assets/projects/openmur/client/client2.webp',
        'assets/projects/openmur/client/client3.webp',
        'assets/projects/openmur/client/client4.webp',
        'assets/projects/openmur/client/client5.webp',
        'assets/projects/openmur/client/client6.webp',
        'assets/projects/openmur/client/client7.webp',
        'assets/projects/openmur/client/client8.webp',
        'assets/projects/openmur/client/client9.webp',
        'assets/projects/openmur/client/client10.webp',
        'assets/projects/openmur/client/client11.webp',
        'assets/projects/openmur/client/client12.webp',
        'assets/projects/openmur/client/client13.webp',
        'assets/projects/openmur/client/client14.webp',
        'assets/projects/openmur/client/client15.webp',
        'assets/projects/openmur/seo/seo1.webp',
        'assets/projects/openmur/seo/seo2.webp',
        'assets/projects/openmur/seo/seo3.webp',
        'assets/projects/openmur/seo/seo4.webp',
        'assets/projects/openmur/seo/seo5.webp',
        'assets/projects/openmur/seo/seo6.webp',
        'assets/projects/openmur/seo/seo7.webp',
        'assets/projects/openmur/seo/seo8.webp',
        'assets/projects/openmur/seo/seo9.webp',
        'assets/projects/openmur/seo/seo10.webp',
        'assets/projects/openmur/seo/seo11.webp',
        'assets/projects/openmur/seo/seo12.webp',
        'assets/projects/openmur/seo/seo13.webp',
        'assets/projects/openmur/seo/seo14.webp',
        'assets/projects/openmur/seo/seo15.webp',
        'assets/projects/openmur/seo/seo16.webp',
        'assets/projects/openmur/seo/seo17.webp',
        'assets/projects/openmur/seo/seo18.webp',
      ],
      demoUrl: 'https://www.open-mur.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Open Mur',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 3,
      title: 'Mes Murs',
      description: '',
      longDescription: '',
      technologies: [
        'Next js',
        'Node.js',
        'Docker',
        'Express js',
        'MongoDB Atlass',
        'Tailwind',
        'TypeScript',
      ],
      category: 'professionnel',
      image: 'assets/projects/mesmurs/mesmurs.webp',
      screenshots: [
        'assets/projects/mesmurs/devis/devis1.webp',
        'assets/projects/mesmurs/devis/devis2.webp',
        'assets/projects/mesmurs/devis/devis3.webp',
        'assets/projects/mesmurs/devis/devis4.webp',
        'assets/projects/mesmurs/devis/devis5.webp',
        'assets/projects/mesmurs/devis/devis6.webp',
        'assets/projects/mesmurs/devis/devis7.webp',
        'assets/projects/mesmurs/devis/devis8.webp',
        'assets/projects/mesmurs/devis/devis9.webp',
        'assets/projects/mesmurs/devis/devis10.webp',
        'assets/projects/mesmurs/admin/admin1.webp',
        'assets/projects/mesmurs/admin/admin2.webp',
        'assets/projects/mesmurs/admin/admin3.webp',
        'assets/projects/mesmurs/admin/admin4.webp',
        'assets/projects/mesmurs/admin/admin5.webp',
        'assets/projects/mesmurs/admin/admin6.webp',
        'assets/projects/mesmurs/admin/admin7.webp',
        'assets/projects/mesmurs/admin/admin8.webp',
        'assets/projects/mesmurs/client/client1.webp',
        'assets/projects/mesmurs/client/client2.webp',
        'assets/projects/mesmurs/client/client3.webp',
        'assets/projects/mesmurs/client/client4.webp',
        'assets/projects/mesmurs/client/client5.webp',
        'assets/projects/mesmurs/client/client6.webp',
        'assets/projects/mesmurs/client/client7.webp',
        'assets/projects/mesmurs/client/client8.webp',
        'assets/projects/mesmurs/client/client9.webp',
        'assets/projects/mesmurs/client/client10.webp',
        'assets/projects/mesmurs/seo/seo1.webp',
        'assets/projects/mesmurs/seo/seo2.webp',
        'assets/projects/mesmurs/seo/seo3.webp',
        'assets/projects/mesmurs/seo/seo4.webp',
        'assets/projects/mesmurs/seo/seo5.webp',
        'assets/projects/mesmurs/seo/seo6.webp',
        'assets/projects/mesmurs/seo/seo7.webp',
        'assets/projects/mesmurs/seo/seo8.webp',
        'assets/projects/mesmurs/seo/seo9.webp',
        'assets/projects/mesmurs/seo/seo10.webp',
        'assets/projects/mesmurs/seo/seo11.webp',
        'assets/projects/mesmurs/seo/seo12.webp',
        'assets/projects/mesmurs/seo/seo13.webp',
        'assets/projects/mesmurs/seo/seo14.webp',
        'assets/projects/mesmurs/seo/seo15.webp',
        'assets/projects/mesmurs/seo/seo16.webp',
      ],
      demoUrl: 'https://www.mesmurs.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Mes Murs',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 4,
      title: 'Mur et Trémie',
      description: '',
      longDescription: '',
      technologies: [
        'Next js',
        'Node.js',
        'Docker',
        'Express js',
        'MongoDB Atlass',
        'Tailwind',
        'TypeScript',
      ],
      category: 'professionnel',
      image: 'assets/projects/muretremie/muretremie.webp',
      screenshots: [
        'assets/projects/muretremie/devis/devis1.webp',
        'assets/projects/muretremie/devis/devis2.webp',
        'assets/projects/muretremie/devis/devis3.webp',
        'assets/projects/muretremie/devis/devis4.webp',
        'assets/projects/muretremie/devis/devis5.webp',
        'assets/projects/muretremie/devis/devis6.webp',
        'assets/projects/muretremie/devis/devis7.webp',
        'assets/projects/muretremie/devis/devis8.webp',
        'assets/projects/muretremie/devis/devis9.webp',
        'assets/projects/muretremie/devis/devis10.webp',
        'assets/projects/muretremie/admin/admin1.webp',
        'assets/projects/muretremie/admin/admin2.webp',
        'assets/projects/muretremie/admin/admin3.webp',
        'assets/projects/muretremie/admin/admin4.webp',
        'assets/projects/muretremie/admin/admin5.webp',
        'assets/projects/muretremie/admin/admin6.webp',
        'assets/projects/muretremie/admin/admin7.webp',
        'assets/projects/muretremie/admin/admin8.webp',
        'assets/projects/muretremie/client/client1.webp',
        'assets/projects/muretremie/client/client2.webp',
        'assets/projects/muretremie/client/client3.webp',
        'assets/projects/muretremie/client/client4.webp',
        'assets/projects/muretremie/client/client5.webp',
        'assets/projects/muretremie/client/client6.webp',
        'assets/projects/muretremie/client/client7.webp',
        'assets/projects/muretremie/client/client8.webp',
        'assets/projects/muretremie/client/client9.webp',
        'assets/projects/muretremie/client/client10.webp',
        'assets/projects/muretremie/seo/seo1.webp',
        'assets/projects/muretremie/seo/seo2.webp',
        'assets/projects/muretremie/seo/seo3.webp',
        'assets/projects/muretremie/seo/seo4.webp',
        'assets/projects/muretremie/seo/seo5.webp',
        'assets/projects/muretremie/seo/seo6.webp',
        'assets/projects/muretremie/seo/seo7.webp',
        'assets/projects/muretremie/seo/seo8.webp',
        'assets/projects/muretremie/seo/seo9.webp',
        'assets/projects/muretremie/seo/seo10.webp',
        'assets/projects/muretremie/seo/seo11.webp',
        'assets/projects/muretremie/seo/seo12.webp',
        'assets/projects/muretremie/seo/seo13.webp',
        'assets/projects/muretremie/seo/seo14.webp',
        'assets/projects/muretremie/seo/seo15.webp',
        'assets/projects/muretremie/seo/seo16.webp',
      ],
      demoUrl: 'https://www.mur-et-tremie.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Mur et Trémie',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 5,
      title: 'Architectis',
      description: '',
      longDescription: '',
      technologies: [
        'Next js',
        'Node.js',
        'Docker',
        'Express js',
        'MongoDB Atlass',
        'Tailwind',
        'TypeScript',
      ],
      category: 'professionnel',
      image: 'assets/projects/architectis/architectis.webp',
      screenshots: [
        'assets/projects/architectis/architectis.webp',
        'assets/projects/architectis/devis/devis1.webp',
        'assets/projects/architectis/devis/devis2.webp',
        'assets/projects/architectis/devis/devis3.webp',
        'assets/projects/architectis/devis/devis4.webp',
        'assets/projects/architectis/devis/devis5.webp',
        'assets/projects/architectis/devis/devis6.webp',
        'assets/projects/architectis/devis/devis7.webp',
        'assets/projects/architectis/devis/devis8.webp',
        'assets/projects/architectis/devis/devis9.webp',
        'assets/projects/architectis/devis/devis10.webp',
        'assets/projects/architectis/admin/admin1.webp',
        'assets/projects/architectis/admin/admin2.webp',
        'assets/projects/architectis/admin/admin3.webp',
        'assets/projects/architectis/admin/admin4.webp',
        'assets/projects/architectis/admin/admin5.webp',
        'assets/projects/architectis/admin/admin6.webp',
        'assets/projects/architectis/admin/admin7.webp',
        'assets/projects/architectis/admin/admin8.webp',
        'assets/projects/architectis/client/client1.webp',
        'assets/projects/architectis/client/client2.webp',
        'assets/projects/architectis/client/client3.webp',
        'assets/projects/architectis/client/client4.webp',
        'assets/projects/architectis/client/client5.webp',
        'assets/projects/architectis/client/client6.webp',
        'assets/projects/architectis/client/client7.webp',
        'assets/projects/architectis/client/client8.webp',
        'assets/projects/architectis/client/client9.webp',
        'assets/projects/architectis/client/client10.webp',
        'assets/projects/architectis/seo/seo1.webp',
        'assets/projects/architectis/seo/seo2.webp',
        'assets/projects/architectis/seo/seo3.webp',
        'assets/projects/architectis/seo/seo4.webp',
        'assets/projects/architectis/seo/seo5.webp',
        'assets/projects/architectis/seo/seo6.webp',
        'assets/projects/architectis/seo/seo7.webp',
        'assets/projects/architectis/seo/seo8.webp',
        'assets/projects/architectis/seo/seo9.webp',
        'assets/projects/architectis/seo/seo10.webp',
        'assets/projects/architectis/seo/seo11.webp',
        'assets/projects/architectis/seo/seo12.webp',
        'assets/projects/architectis/seo/seo13.webp',
        'assets/projects/architectis/seo/seo14.webp',
        'assets/projects/architectis/seo/seo15.webp',
        'assets/projects/architectis/seo/seo16.webp',
      ],
      demoUrl: 'https://www.architectis.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Mur et Trémie',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 6,
      title: 'Maison Presto',
      description: '',
      longDescription: '',
      technologies: [
        'Next js',
        'Docker',
        'Node.js',
        'Express js',
        'MongoDB Atlass',
        'Tailwind',
        'TypeScript',
      ],
      category: 'professionnel',
      image: 'assets/projects/maisonpresto/maisonpresto.webp',
      screenshots: [
        'assets/projects/maisonpresto/devis/devis1.webp',
        'assets/projects/maisonpresto/devis/devis2.webp',
        'assets/projects/maisonpresto/devis/devis3.webp',
        'assets/projects/maisonpresto/devis/devis4.webp',
        'assets/projects/maisonpresto/devis/devis5.webp',
        'assets/projects/maisonpresto/devis/devis6.webp',
        'assets/projects/maisonpresto/devis/devis7.webp',
        'assets/projects/maisonpresto/devis/devis8.webp',
        'assets/projects/maisonpresto/devis/devis9.webp',
        'assets/projects/maisonpresto/devis/devis10.webp',
        'assets/projects/maisonpresto/devis/devis11.webp',
        'assets/projects/maisonpresto/admin/admin1.webp',
        'assets/projects/maisonpresto/admin/admin2.webp',
        'assets/projects/maisonpresto/admin/admin3.webp',
        'assets/projects/maisonpresto/admin/admin4.webp',
        'assets/projects/maisonpresto/admin/admin5.webp',
        'assets/projects/maisonpresto/admin/admin6.webp',
        'assets/projects/maisonpresto/admin/admin7.webp',
        'assets/projects/maisonpresto/admin/admin8.webp',
        'assets/projects/maisonpresto/admin/admin9.webp',
        'assets/projects/maisonpresto/admin/admin10.webp',
        'assets/projects/maisonpresto/admin/admin11.webp',
        'assets/projects/maisonpresto/admin/admin12.webp',
        'assets/projects/maisonpresto/admin/admin13.webp',
        'assets/projects/maisonpresto/admin/admin14.webp',
        'assets/projects/maisonpresto/admin/admin15.webp',
        'assets/projects/maisonpresto/admin/admin16.webp',
        'assets/projects/maisonpresto/admin/admin17.webp',
        'assets/projects/maisonpresto/client/client1.webp',
        'assets/projects/maisonpresto/client/client2.webp',
        'assets/projects/maisonpresto/client/client3.webp',
        'assets/projects/maisonpresto/client/client4.webp',
        'assets/projects/maisonpresto/client/client5.webp',
        'assets/projects/maisonpresto/client/client6.webp',
        'assets/projects/maisonpresto/client/client7.webp',
        'assets/projects/maisonpresto/client/client8.webp',
        'assets/projects/maisonpresto/client/client9.webp',
        'assets/projects/maisonpresto/client/client10.webp',
        'assets/projects/maisonpresto/client/client11.webp',
        'assets/projects/maisonpresto/client/client12.webp',
        'assets/projects/maisonpresto/client/client13.webp',
        'assets/projects/maisonpresto/client/client14.webp',
        'assets/projects/maisonpresto/client/client15.webp',
        'assets/projects/maisonpresto/seo/seo1.webp',
        'assets/projects/maisonpresto/seo/seo2.webp',
        'assets/projects/maisonpresto/seo/seo3.webp',
        'assets/projects/maisonpresto/seo/seo4.webp',
        'assets/projects/maisonpresto/seo/seo5.webp',
        'assets/projects/maisonpresto/seo/seo6.webp',
        'assets/projects/maisonpresto/seo/seo7.webp',
        'assets/projects/maisonpresto/seo/seo8.webp',
        'assets/projects/maisonpresto/seo/seo9.webp',
        'assets/projects/maisonpresto/seo/seo10.webp',
        'assets/projects/maisonpresto/seo/seo11.webp',
        'assets/projects/maisonpresto/seo/seo12.webp',
        'assets/projects/maisonpresto/seo/seo13.webp',
        'assets/projects/maisonpresto/seo/seo14.webp',
        'assets/projects/maisonpresto/seo/seo15.webp',
        'assets/projects/maisonpresto/seo/seo16.webp',
        'assets/projects/maisonpresto/seo/seo17.webp',
        'assets/projects/maisonpresto/seo/seo18.webp',
      ],
      demoUrl: 'https://maison-presto.com',
      githubUrl: 'https://github.com/votre-projet/ecommerce',
      year: 2024,
      client: 'Maison Presto',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 7,
      title: 'Utopik',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/utopik/utopik.webp',
      screenshots: ['assets/projects/utopik/utopik.webp'],
      demoUrl: 'https://utopik-communication.fr',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Utopik',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 8,
      title: 'Utopik international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/utopikinter/utopikinter.webp',
      screenshots: ['assets/projects/utopikinter/utopikinter.webp'],
      demoUrl: 'https://www.utopik-communication.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Utopik',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 9,
      title: 'Cekterys',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/cekterys/cekterys.webp',
      screenshots: ['assets/projects/cekterys/cekterys.webp'],
      demoUrl: 'https://www.utopik-communication.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Cekterys',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 10,
      title: 'Finky',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/finky/finky.webp',
      screenshots: ['assets/projects/finky/finky.webp'],
      demoUrl: 'https://www.finky-consulting.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Finky',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 11,
      title: 'Inchaate',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/inchaate/inchaate.webp',
      screenshots: ['assets/projects/inchaate/inchaate.webp'],
      demoUrl: 'https://www.inchaate.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Inchaate',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 12,
      title: 'Inchaate international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/inchaateinter/inchaateinter.webp',
      screenshots: ['assets/projects/inchaateinter/inchaateinter.webp'],
      demoUrl: 'https://inchaate.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Inchaate',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 13,
      title: 'Sportneo',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/sportneo/sportneo.webp',
      screenshots: ['assets/projects/sportneo/sportneo.webp'],
      demoUrl: 'https://lightslategray-nightingale-538581.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Sportneo',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 14,
      title: 'Batrino',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/batrino/batrino.webp',
      screenshots: ['assets/projects/batrino/batrino.webp'],
      demoUrl: 'https://www.sienna-squid-376436.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Batrino',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 15,
      title: 'Linkea',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/linkea/linkea.webp',
      screenshots: ['assets/projects/linkea/linkea.webp'],
      demoUrl: 'https://www.linkea-consulting.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Linkea',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 16,
      title: 'Linkea international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/linkeainter/linkeainter.webp',
      screenshots: ['assets/projects/linkeainter/linkeainter.webp'],
      demoUrl: 'https://linkea-consulting.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Linkea',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 17,
      title: 'EGBTP',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/egbtp/egbtp.webp',
      screenshots: ['assets/projects/egbtp/egbtp.webp'],
      demoUrl: 'https://ghostwhite-beaver-862090.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'EGBTP',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 18,
      title: 'Piscineo',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/piscineo/piscineo.webp',
      screenshots: ['assets/projects/piscineo/piscineo.webp'],
      demoUrl: 'https://piscineo-tunisie.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Piscineo',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 19,
      title: 'Strategys international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/strategysinter/strategysinter.webp',
      screenshots: ['assets/projects/strategysinter/strategysinter.webp'],
      demoUrl: 'https://strategys-international.com ',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Strategys',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 20,
      title: 'Strategys',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/strategys/strategys.webp',
      screenshots: ['assets/projects/strategys/strategys.webp'],
      demoUrl: 'https://strategys-international.com ',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Strategys',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 21,
      title: 'Enirop',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/enirop/enirop.webp',
      screenshots: ['assets/projects/enirop/enirop.webp'],
      demoUrl: 'https://enirop.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Enirop',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 22,
      title: 'Sopranet',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/sopranet/sopranet.webp',
      screenshots: ['assets/projects/sopranet/sopranet.webp'],
      demoUrl: 'https://sopranet.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Sopranet',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 23,
      title: 'Reno Global',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/renoglobal/renoglobal.webp',
      screenshots: ['assets/projects/renoglobal/renoglobal.webp'],
      demoUrl: 'https://www.global-reno.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Reno Global',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 24,
      title: 'Klass Design',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/klassdesign/klassdesign.webp',
      screenshots: ['assets/projects/klassdesign/klassdesign.webp'],
      demoUrl: 'https://klass-design.fr',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Klass Design',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 25,
      title: '1001 Architectures',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/1001architectures/1001architectures.webp',
      screenshots: ['assets/projects/1001architectures/1001architectures.webp'],
      demoUrl: 'https://1001-architectures.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: '1001 Architectures',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 26,
      title: 'Reno deco',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/renodeco/renodeco.webp',
      screenshots: ['assets/projects/renodeco/renodeco.webp'],
      demoUrl: 'https://reno-deco.fr',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Reno deco',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 27,
      title: 'Spacy and Cosy',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/spacyandcosy/spacyandcosy.webp',
      screenshots: ['assets/projects/spacyandcosy/spacyandcosy.webp'],
      demoUrl: 'https://www.spacy-and-cosy.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Spacy and Cosy',
      duration: '3 mois',
      team: 'Équipe de 2 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 28,
      title: 'Luxury and Cosy',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/luxuryandcosy/luxuryandcosy.webp',
      screenshots: ['assets/projects/luxuryandcosy/luxuryandcosy.webp'],
      demoUrl: 'https://pink-antelope-778957.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Luxury and Cosy',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 29,
      title: 'Renov en main',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/renovenmain/renovenmain.webp',
      screenshots: ['assets/projects/renovenmain/renovenmain.webp'],
      demoUrl: 'https://renov-en-main.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Renov en main',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 30,
      title: 'Archilux',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/archilux/archilux.webp',
      screenshots: ['assets/projects/archilux/archilux.webp'],
      demoUrl: 'https://www.archi-lux.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Archilux',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 31,
      title: 'Agexis',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/agexis/agexis.webp',
      screenshots: ['assets/projects/agexis/agexis.webp'],
      demoUrl: 'https://www.agexis.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Agexis',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 32,
      title: 'AB Engineering',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/abengineering/abengineering.webp',
      screenshots: ['assets/projects/abengineering/abengineering.webp'],
      demoUrl: 'https://www.ab-engineering.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'AB Engineering',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 33,
      title: 'Gex Batiment',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/gexbatiment/gexbatiment.webp',
      screenshots: ['assets/projects/gexbatiment/gexbatiment.webp'],
      demoUrl: 'https://www.gex-batiment.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Gex Batiment',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 34,
      title: 'Eneahome',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/eneahome/eneahome.webp',
      screenshots: ['assets/projects/eneahome/eneahome.webp'],
      demoUrl: 'https://www.eneahome.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Eneahome',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 35,
      title: 'Wellton',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/wellton/wellton.webp',
      screenshots: ['assets/projects/wellton/wellton.webp'],
      demoUrl: 'https://www.wellton-consulting.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Wellton',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 36,
      title: 'Structural Home',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/structuralhome/structuralhome.webp',
      screenshots: ['assets/projects/structuralhome/structuralhome.webp'],
      demoUrl: 'https://www.structural-home.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Structural Home',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 37,
      title: 'Structural Steel',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/structuralsteel/structuralsteel.webp',
      screenshots: ['assets/projects/structuralsteel/structuralsteel.webp'],
      demoUrl: 'https://www.structural-metal.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Structural Steel',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 38,
      title: 'Structural Wood',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/structuralwood/structuralwood.webp',
      screenshots: ['assets/projects/structuralwood/structuralwood.webp'],
      demoUrl: 'https://www.structural-wood.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Structural Wood',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 39,
      title: 'Automatisation des déploiements Kubernetes - 3S',
      description: '',
      longDescription: '',
      technologies: ['Kubernetes', 'Ansible', 'ArgoCD'],
      category: 'academique',
      image: 'assets/projects/pfe3s/pfe3s.webp',
      screenshots: [
        'assets/projects/pfe3s/pfe3s.webp',
        'assets/projects/pfe3s/pfe3s1.webp',
        'assets/projects/pfe3s/pfe3s2.webp',
        'assets/projects/pfe3s/pfe3s3.webp',
        'assets/projects/pfe3s/pfe3s4.webp',
        'assets/projects/pfe3s/pfe3s5.webp',
        'assets/projects/pfe3s/pfe3s6.webp',
        'assets/projects/pfe3s/pfe3s7.webp',
      ],
      demoUrl: '',
      githubUrl: '',
      year: 2025,
      client: '3S',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 40,
      title: 'AB Projects',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/abprojects/abprojects.webp',
      screenshots: ['assets/projects/abprojects/abprojects.webp'],
      demoUrl: 'https://www.ab-pro.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'AB Projects',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 41,
      title: 'Giovanni Juvara',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/giovannijuvara/giovannijuvara.webp',
      screenshots: ['assets/projects/giovannijuvara/giovannijuvara.webp'],
      demoUrl: 'https://www.giovanni-juvara.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Giovanni Juvara',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 42,
      title: 'Facilities',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/facilities/facilities.webp',
      screenshots: ['assets/projects/facilities/facilities.webp'],
      demoUrl: 'https://facilitys-international.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Facilities',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 43,
      title: 'Modulo20',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/modulo20/modulo20.webp',
      screenshots: ['assets/projects/modulo20/modulo20.webp'],
      demoUrl: 'https://www.modulo20.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Modulo20',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 44,
      title: 'Agexea Energie',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/agexeaenergie/agexeaenergie.webp',
      screenshots: ['assets/projects/agexeaenergie/agexeaenergie.webp'],
      demoUrl: 'https://www.agexea-energie.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Agexea Energie',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 45,
      title: 'Eneapro',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/eneapro/eneapro.webp',
      screenshots: ['assets/projects/eneapro/eneapro.webp'],
      demoUrl: 'https://www.eneapro.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Eneapro',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 46,
      title: 'Karriery',
      description: '',
      longDescription: '',
      technologies: ['Angular', 'Material UI', 'Boostrap', 'Node js'],
      category: 'auto-formation',
      image: 'assets/projects/karriery/karriery1.webp',
      screenshots: [
        'assets/projects/karriery/karriery1.webp',
        'assets/projects/karriery/karriery2.webp',
        'assets/projects/karriery/karriery3.webp',
        'assets/projects/karriery/karriery4.webp',
        'assets/projects/karriery/karriery5.webp',
        'assets/projects/karriery/karriery6.webp',
        'assets/projects/karriery/karriery7.webp',
        'assets/projects/karriery/karriery8.webp',
        'assets/projects/karriery/karriery9.webp',
        'assets/projects/karriery/karriery10.webp',
        'assets/projects/karriery/karriery11.webp',
        'assets/projects/karriery/karriery12.webp',
        'assets/projects/karriery/karriery13.webp',
        'assets/projects/karriery/karriery14.webp',
      ],
      demoUrl: '',
      githubUrl: '',
      year: 2024,
      client: 'Karriery',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 47,
      title: 'Constat',
      description: '',
      longDescription: '',
      technologies: ['Nest js', 'Angular', 'Material UI', 'Boostrap'],
      category: 'freelance',
      image: 'assets/projects/constat/constat1.webp',
      screenshots: [
        'assets/projects/constat/constat1.webp',
        'assets/projects/constat/constat2.webp',
        'assets/projects/constat/constat3.webp',
        'assets/projects/constat/constat4.webp',
        'assets/projects/constat/constat5.webp',
        'assets/projects/constat/constat6.webp',
        'assets/projects/constat/constat7.webp',
        'assets/projects/constat/constat8.webp',
      ],
      demoUrl: '',
      githubUrl: '',
      year: 2024,
      client: 'Karriery',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 48,
      title: 'Romain',
      description: '',
      longDescription: '',
      technologies: ['Angular', 'Material UI', 'Boostrap', 'Nest js'],
      category: 'freelance',
      image: 'assets/projects/romain/romain1.webp',
      screenshots: [
        'assets/projects/romain/romain1.webp',
        'assets/projects/romain/romain2.webp',
        'assets/projects/romain/romain3.webp',
        'assets/projects/romain/romain4.webp',
        'assets/projects/romain/romain5.webp',
        'assets/projects/romain/romain6.webp',
        'assets/projects/romain/romain7.webp',
        'assets/projects/romain/romain8.webp',
        'assets/projects/romain/romain9.webp',
        'assets/projects/romain/romain10.webp',
        'assets/projects/romain/romain11.webp',
        'assets/projects/romain/romain12.webp',
      ],
      demoUrl: 'https://romain.care',
      githubUrl: '',
      year: 2024,
      client: 'Karriery',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 49,
      title: 'Sybernetys international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/sybernetysinter/sybernetysinter.webp',
      screenshots: ['assets/projects/sybernetysinter/sybernetysinter.webp'],
      demoUrl: 'https://sybernetys-international.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Sybernetys international',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 50,
      title: 'Sybernetys',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/sybernetys/sybernetys.webp',
      screenshots: ['assets/projects/sybernetys/sybernetys.webp'],
      demoUrl: 'https://www.sybernetys.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Sybernetys',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 51,
      title: 'Constat',
      description: '',
      longDescription: '',
      technologies: ['Nest js', 'Ionic', 'Figma'],
      category: 'freelance',
      image: 'assets/projects/constatmobile/constat1.webp',
      screenshots: [
        'assets/projects/constatmobile/constat1.webp',
        'assets/projects/constatmobile/constat2.webp',
        'assets/projects/constatmobile/constat3.webp',
        'assets/projects/constatmobile/constat4.webp',
        'assets/projects/constatmobile/constat5.webp',
        'assets/projects/constatmobile/constat6.webp',
        'assets/projects/constatmobile/constat7.webp',
        'assets/projects/constatmobile/constat8.webp',
      ],
      demoUrl: '',
      githubUrl: '',
      year: 2024,
      client: 'Karriery',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 52,
      title: 'Welldup',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/welldup/welldup.webp',
      screenshots: ['assets/projects/welldup/welldup.webp'],
      demoUrl: 'https://www.welldup.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Welldup',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 53,
      title: 'Ingenerium',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/ingenerium/ingenerium.webp',
      screenshots: ['assets/projects/ingenerium/ingenerium.webp'],
      demoUrl: 'https://www.ingenerium.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Ingenerium',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 54,
      title: 'Surfcom',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/surfcom/surfcom.webp',
      screenshots: ['assets/projects/surfcom/surfcom.webp'],
      demoUrl: 'https://surf-com.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Surfcom',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 55,
      title: 'Centorys',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/centorys/centorys.webp',
      screenshots: ['assets/projects/centorys/centorys.webp'],
      demoUrl: 'https://www.centorys.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Centorys',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 56,
      title: 'Ikonoklass',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/ikonoklass/ikonoklass.webp',
      screenshots: ['assets/projects/ikonoklass/ikonoklass.webp'],
      demoUrl: 'https://www.ikonoklass.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Ikonoklass',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 57,
      title: 'Eneatec',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/eneatec/eneatec.webp',
      screenshots: ['assets/projects/eneatec/eneatec.webp'],
      demoUrl: 'https://www.enea-construction.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Eneatec',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 58,
      title: 'Recopneu',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Tailwind', 'TypeScript'],
      category: 'freelance',
      image: 'assets/projects/recopneu/recopneu.webp',
      screenshots: ['assets/projects/recopneu/recopneu.webp'],
      demoUrl: 'https://recopneu-j8cskhkwd-nesrines-projects-d410c266.vercel.app/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2026,
      client: 'Recopneu',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 59,
      title: 'Graphic Center',
      description: '',
      longDescription: '',
      technologies: ['HTML', 'scss', 'JavaScript', 'Boostrap'],
      category: 'freelance',
      image: 'assets/projects/graphiccenter/graphiccenter.webp',
      screenshots: ['assets/projects/graphiccenter/graphiccenter.webp'],
      demoUrl: 'https://www.graphiccentertn.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2023,
      client: 'Graphic Center',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 60,
      title: 'Agexmail',
      description: 'Automatisation de la création et de la configuration des e-mails OVH',
      longDescription: '',
      technologies: [
        'PowerShell',
        'Next js',
        'Tailwind',
        'Node js',
        'Docker',
        'Docker compose',
        'python',
        'Express js',
        'MongoDB Atlass',
      ],
      category: 'professionnel',
      image: 'assets/projects/agexmail/agexmail.webp',
      screenshots: ['assets/projects/agexmail/agexmail.webp'],
      demoUrl: 'professionnel',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Agexis',
      duration: '3 semaines',
      team: 'Équipe de 3 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 61,
      title: 'Déchargeur de batteries - SNCFT',
      description: '',
      longDescription: '',
      technologies: ['MatLab', 'Arduino'],
      category: 'academique',
      image: 'assets/projects/pfesnfct/pfesnfct.webp',
      screenshots: [
        'assets/projects/pfesnfct/pfesnfct.webp',
        'assets/projects/pfesnfct/pfesnfct1.webp',
        'assets/projects/pfesnfct/pfesnfct2.webp',
        'assets/projects/pfesnfct/pfesnfct3.webp',
        'assets/projects/pfesnfct/pfesnfct4.webp',
        'assets/projects/pfesnfct/pfesnfct5.webp',
        'assets/projects/pfesnfct/pfesnfct6.webp',
        'assets/projects/pfesnfct/pfesnfct7.webp',
      ],
      demoUrl: '',
      githubUrl: '',
      year: 2025,
      client: 'SNCFT',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 62,
      title: 'My Note',
      description: '',
      longDescription: '',
      technologies: ['React Native', 'Figma'],
      category: 'freelance',
      image: 'assets/projects/mynote/mynote1.webp',
      screenshots: [
        'assets/projects/mynote/mynote1.webp',
        'assets/projects/mynote/mynote2.webp',
        'assets/projects/mynote/mynote3.webp',
        'assets/projects/mynote/mynote4.webp',
        'assets/projects/mynote/mynote5.webp',
      ],
      demoUrl: '',
      githubUrl: '',
      year: 2024,
      client: 'Acil ZAITER',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
  ];

  getProjects(): IProject[] {
    console.log('Tous les projets :', this.projects);
    return this.projects;
  }

  getProjectById(id: number): IProject | undefined {
    console.log('Recherche du projet avec ID :', id);
    console.log(
      'Projets disponibles :',
      this.projects.map((p) => p.id),
    );
    const project = this.projects.find((p) => p.id === id);
    console.log('Projet trouvé :', project);
    return project;
  }

  getTechnologies(): string[] {
    const techSet = new Set<string>();
    this.projects.forEach((p) => p.technologies.forEach((t) => techSet.add(t)));
    return Array.from(techSet).sort();
  }
}
