// services/project.service.ts
import { Injectable } from '@angular/core';

export interface IProject {
  id: number;
  title: string;
  description: string;
  longDescription?: string;
  technologies: string[];
  category: 'academique' | 'auto-formation' | 'professionnel' | 'freelance';
  image: string;
  screenshots?: string[];
  demoUrl?: string;
  githubUrl?: string;
  year: number;
  client?: string;
  duration?: string;
  team?: string;
  challenges?: string[];
  features?: string[];
}

@Injectable({
  providedIn: 'root',
})
export class ProjectService {
  private projects: IProject[] = [
    {
      id: 1,
      title: 'Mur Mur',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/murmur/murmur.png',
      screenshots: [
        'assets/projects/murmur/devis/devis1.png',
        'assets/projects/murmur/devis/devis2.png',
        'assets/projects/murmur/devis/devis3.png',
        'assets/projects/murmur/devis/devis4.png',
        'assets/projects/murmur/devis/devis5.png',
        'assets/projects/murmur/devis/devis6.png',
        'assets/projects/murmur/devis/devis7.png',
        'assets/projects/murmur/devis/devis8.png',
        'assets/projects/murmur/devis/devis9.png',
        'assets/projects/murmur/devis/devis10.png',
        'assets/projects/murmur/devis/devis11.png',
        'assets/projects/murmur/admin/admin1.png',
        'assets/projects/murmur/admin/admin2.png',
        'assets/projects/murmur/admin/admin3.png',
        'assets/projects/murmur/admin/admin4.png',
        'assets/projects/murmur/admin/admin5.png',
        'assets/projects/murmur/admin/admin6.png',
        'assets/projects/murmur/admin/admin7.png',
        'assets/projects/murmur/admin/admin8.png',
        'assets/projects/murmur/admin/admin9.png',
        'assets/projects/murmur/admin/admin10.png',
        'assets/projects/murmur/admin/admin11.png',
        'assets/projects/murmur/admin/admin12.png',
        'assets/projects/murmur/admin/admin13.png',
        'assets/projects/murmur/admin/admin14.png',
        'assets/projects/murmur/admin/admin15.png',
        'assets/projects/murmur/admin/admin16.png',
        'assets/projects/murmur/admin/admin17.png',
        'assets/projects/murmur/client/client1.png',
        'assets/projects/murmur/client/client2.png',
        'assets/projects/murmur/client/client3.png',
        'assets/projects/murmur/client/client4.png',
        'assets/projects/murmur/client/client5.png',
        'assets/projects/murmur/client/client6.png',
        'assets/projects/murmur/client/client7.png',
        'assets/projects/murmur/client/client8.png',
        'assets/projects/murmur/client/client9.png',
        'assets/projects/murmur/client/client10.png',
        'assets/projects/murmur/client/client11.png',
        'assets/projects/murmur/client/client12.png',
        'assets/projects/murmur/client/client13.png',
        'assets/projects/murmur/client/client14.png',
        'assets/projects/murmur/client/client15.png',
        'assets/projects/murmur/seo/seo1.png',
        'assets/projects/murmur/seo/seo2.png',
        'assets/projects/murmur/seo/seo3.png',
        'assets/projects/murmur/seo/seo4.png',
        'assets/projects/murmur/seo/seo5.png',
        'assets/projects/murmur/seo/seo6.png',
        'assets/projects/murmur/seo/seo7.png',
        'assets/projects/murmur/seo/seo8.png',
        'assets/projects/murmur/seo/seo9.png',
        'assets/projects/murmur/seo/seo10.png',
        'assets/projects/murmur/seo/seo11.png',
        'assets/projects/murmur/seo/seo12.png',
        'assets/projects/murmur/seo/seo13.png',
        'assets/projects/murmur/seo/seo14.png',
        'assets/projects/murmur/seo/seo15.png',
        'assets/projects/murmur/seo/seo16.png',
        'assets/projects/murmur/seo/seo17.png',
        'assets/projects/murmur/seo/seo18.png',
      ],
      demoUrl: 'https://www.mur-mur.fr/',
      githubUrl: 'https://github.com/votre-projet/ecommerce',
      year: 2024,
      client: 'Mur Mur',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 2,
      title: 'Open Mur',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/openmur/openmur.webp',
      screenshots: [
        'assets/projects/openmur/devis/devis1.webp',
        'assets/projects/openmur/devis/devis2.webp',
        'assets/projects/openmur/devis/devis3.webp',
        'assets/projects/openmur/admin/admin1.webp',
        'assets/projects/openmur/admin/admin2.webp',
        'assets/projects/openmur/admin/admin3.webp',
        'assets/projects/openmur/admin/admin4.webp',
        'assets/projects/openmur/admin/admin5.webp',
        'assets/projects/openmur/admin/admin6.webp',
        'assets/projects/openmur/admin/admin7.webp',
        'assets/projects/openmur/admin/admin8.webp',
        'assets/projects/openmur/admin/admin9.webp',
        'assets/projects/openmur/admin/admin10.webp',
        'assets/projects/openmur/admin/admin11.webp',
        'assets/projects/openmur/admin/admin12.webp',
        'assets/projects/openmur/admin/admin13.webp',
        'assets/projects/openmur/admin/admin14.webp',
        'assets/projects/openmur/admin/admin15.webp',
        'assets/projects/openmur/admin/admin16.webp',
        'assets/projects/openmur/admin/admin17.webp',
        'assets/projects/openmur/client/client1.webp',
        'assets/projects/openmur/client/client2.webp',
        'assets/projects/openmur/client/client3.webp',
        'assets/projects/openmur/client/client4.webp',
        'assets/projects/openmur/client/client5.webp',
        'assets/projects/openmur/client/client6.webp',
        'assets/projects/openmur/client/client7.webp',
        'assets/projects/openmur/client/client8.webp',
        'assets/projects/openmur/client/client9.webp',
        'assets/projects/openmur/client/client10.webp',
        'assets/projects/openmur/client/client11.webp',
        'assets/projects/openmur/client/client12.webp',
        'assets/projects/openmur/client/client13.webp',
        'assets/projects/openmur/client/client14.webp',
        'assets/projects/openmur/client/client15.webp',
        'assets/projects/openmur/seo/seo1.webp',
        'assets/projects/openmur/seo/seo2.webp',
        'assets/projects/openmur/seo/seo3.webp',
        'assets/projects/openmur/seo/seo4.webp',
        'assets/projects/openmur/seo/seo5.webp',
        'assets/projects/openmur/seo/seo6.webp',
        'assets/projects/openmur/seo/seo7.webp',
        'assets/projects/openmur/seo/seo8.webp',
        'assets/projects/openmur/seo/seo9.webp',
        'assets/projects/openmur/seo/seo10.webp',
        'assets/projects/openmur/seo/seo11.webp',
        'assets/projects/openmur/seo/seo12.webp',
        'assets/projects/openmur/seo/seo13.webp',
        'assets/projects/openmur/seo/seo14.webp',
        'assets/projects/openmur/seo/seo15.webp',
        'assets/projects/openmur/seo/seo16.webp',
        'assets/projects/openmur/seo/seo17.webp',
        'assets/projects/openmur/seo/seo18.webp',
      ],
      demoUrl: 'https://www.open-mur.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Open Mur',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 3,
      title: 'Mes Murs',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/mesmurs/mesmurs.webp',
      screenshots: [
        'assets/projects/mesmurs/devis/devis1.webp',
        'assets/projects/mesmurs/devis/devis2.webp',
        'assets/projects/mesmurs/devis/devis3.webp',
        'assets/projects/mesmurs/devis/devis4.webp',
        'assets/projects/mesmurs/devis/devis5.webp',
        'assets/projects/mesmurs/devis/devis6.webp',
        'assets/projects/mesmurs/devis/devis7.webp',
        'assets/projects/mesmurs/devis/devis8.webp',
        'assets/projects/mesmurs/devis/devis9.webp',
        'assets/projects/mesmurs/devis/devis10.webp',
        'assets/projects/mesmurs/admin/admin1.webp',
        'assets/projects/mesmurs/admin/admin2.webp',
        'assets/projects/mesmurs/admin/admin3.webp',
        'assets/projects/mesmurs/admin/admin4.webp',
        'assets/projects/mesmurs/admin/admin5.webp',
        'assets/projects/mesmurs/admin/admin6.webp',
        'assets/projects/mesmurs/admin/admin7.webp',
        'assets/projects/mesmurs/admin/admin8.webp',
        'assets/projects/mesmurs/client/client1.webp',
        'assets/projects/mesmurs/client/client2.webp',
        'assets/projects/mesmurs/client/client3.webp',
        'assets/projects/mesmurs/client/client4.webp',
        'assets/projects/mesmurs/client/client5.webp',
        'assets/projects/mesmurs/client/client6.webp',
        'assets/projects/mesmurs/client/client7.webp',
        'assets/projects/mesmurs/client/client8.webp',
        'assets/projects/mesmurs/client/client9.webp',
        'assets/projects/mesmurs/client/client10.webp',
        'assets/projects/mesmurs/seo/seo1.webp',
        'assets/projects/mesmurs/seo/seo2.webp',
        'assets/projects/mesmurs/seo/seo3.webp',
        'assets/projects/mesmurs/seo/seo4.webp',
        'assets/projects/mesmurs/seo/seo5.webp',
        'assets/projects/mesmurs/seo/seo6.webp',
        'assets/projects/mesmurs/seo/seo7.webp',
        'assets/projects/mesmurs/seo/seo8.webp',
        'assets/projects/mesmurs/seo/seo9.webp',
        'assets/projects/mesmurs/seo/seo10.webp',
        'assets/projects/mesmurs/seo/seo11.webp',
        'assets/projects/mesmurs/seo/seo12.webp',
        'assets/projects/mesmurs/seo/seo13.webp',
        'assets/projects/mesmurs/seo/seo14.webp',
        'assets/projects/mesmurs/seo/seo15.webp',
        'assets/projects/mesmurs/seo/seo16.webp',
      ],
      demoUrl: 'https://www.mesmurs.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Mes Murs',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 4,
      title: 'Mur et Trémie',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/muretremie/muretremie.webp',
      screenshots: [
        'assets/projects/muretremie/devis/devis1.webp',
        'assets/projects/muretremie/devis/devis2.webp',
        'assets/projects/muretremie/devis/devis3.webp',
        'assets/projects/muretremie/devis/devis4.webp',
        'assets/projects/muretremie/devis/devis5.webp',
        'assets/projects/muretremie/devis/devis6.webp',
        'assets/projects/muretremie/devis/devis7.webp',
        'assets/projects/muretremie/devis/devis8.webp',
        'assets/projects/muretremie/devis/devis9.webp',
        'assets/projects/muretremie/devis/devis10.webp',
        'assets/projects/muretremie/admin/admin1.webp',
        'assets/projects/muretremie/admin/admin2.webp',
        'assets/projects/muretremie/admin/admin3.webp',
        'assets/projects/muretremie/admin/admin4.webp',
        'assets/projects/muretremie/admin/admin5.webp',
        'assets/projects/muretremie/admin/admin6.webp',
        'assets/projects/muretremie/admin/admin7.webp',
        'assets/projects/muretremie/admin/admin8.webp',
        'assets/projects/muretremie/client/client1.webp',
        'assets/projects/muretremie/client/client2.webp',
        'assets/projects/muretremie/client/client3.webp',
        'assets/projects/muretremie/client/client4.webp',
        'assets/projects/muretremie/client/client5.webp',
        'assets/projects/muretremie/client/client6.webp',
        'assets/projects/muretremie/client/client7.webp',
        'assets/projects/muretremie/client/client8.webp',
        'assets/projects/muretremie/client/client9.webp',
        'assets/projects/muretremie/client/client10.webp',
        'assets/projects/muretremie/seo/seo1.webp',
        'assets/projects/muretremie/seo/seo2.webp',
        'assets/projects/muretremie/seo/seo3.webp',
        'assets/projects/muretremie/seo/seo4.webp',
        'assets/projects/muretremie/seo/seo5.webp',
        'assets/projects/muretremie/seo/seo6.webp',
        'assets/projects/muretremie/seo/seo7.webp',
        'assets/projects/muretremie/seo/seo8.webp',
        'assets/projects/muretremie/seo/seo9.webp',
        'assets/projects/muretremie/seo/seo10.webp',
        'assets/projects/muretremie/seo/seo11.webp',
        'assets/projects/muretremie/seo/seo12.webp',
        'assets/projects/muretremie/seo/seo13.webp',
        'assets/projects/muretremie/seo/seo14.webp',
        'assets/projects/muretremie/seo/seo15.webp',
        'assets/projects/muretremie/seo/seo16.webp',
      ],
      demoUrl: 'https://www.mur-et-tremie.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Mur et Trémie',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 5,
      title: 'Architectis',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/architectis/architectis.webp',
      screenshots: [
        'assets/projects/architectis/architectis.webp',
        'assets/projects/architectis/devis/devis1.webp',
        'assets/projects/architectis/devis/devis2.webp',
        'assets/projects/architectis/devis/devis3.webp',
        'assets/projects/architectis/devis/devis4.webp',
        'assets/projects/architectis/devis/devis5.webp',
        'assets/projects/architectis/devis/devis6.webp',
        'assets/projects/architectis/devis/devis7.webp',
        'assets/projects/architectis/devis/devis8.webp',
        'assets/projects/architectis/devis/devis9.webp',
        'assets/projects/architectis/devis/devis10.webp',
        'assets/projects/architectis/admin/admin1.webp',
        'assets/projects/architectis/admin/admin2.webp',
        'assets/projects/architectis/admin/admin3.webp',
        'assets/projects/architectis/admin/admin4.webp',
        'assets/projects/architectis/admin/admin5.webp',
        'assets/projects/architectis/admin/admin6.webp',
        'assets/projects/architectis/admin/admin7.webp',
        'assets/projects/architectis/admin/admin8.webp',
        'assets/projects/architectis/client/client1.webp',
        'assets/projects/architectis/client/client2.webp',
        'assets/projects/architectis/client/client3.webp',
        'assets/projects/architectis/client/client4.webp',
        'assets/projects/architectis/client/client5.webp',
        'assets/projects/architectis/client/client6.webp',
        'assets/projects/architectis/client/client7.webp',
        'assets/projects/architectis/client/client8.webp',
        'assets/projects/architectis/client/client9.webp',
        'assets/projects/architectis/client/client10.webp',
        'assets/projects/architectis/seo/seo1.webp',
        'assets/projects/architectis/seo/seo2.webp',
        'assets/projects/architectis/seo/seo3.webp',
        'assets/projects/architectis/seo/seo4.webp',
        'assets/projects/architectis/seo/seo5.webp',
        'assets/projects/architectis/seo/seo6.webp',
        'assets/projects/architectis/seo/seo7.webp',
        'assets/projects/architectis/seo/seo8.webp',
        'assets/projects/architectis/seo/seo9.webp',
        'assets/projects/architectis/seo/seo10.webp',
        'assets/projects/architectis/seo/seo11.webp',
        'assets/projects/architectis/seo/seo12.webp',
        'assets/projects/architectis/seo/seo13.webp',
        'assets/projects/architectis/seo/seo14.webp',
        'assets/projects/architectis/seo/seo15.webp',
        'assets/projects/architectis/seo/seo16.webp',
      ],
      demoUrl: 'https://www.architectis.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Mur et Trémie',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 6,
      title: 'Luxury and Cosy',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/luxuryandcosy/luxuryandcosy.webp',
      screenshots: ['assets/projects/luxuryandcosy/luxuryandcosy.webp'],
      demoUrl: 'https://pink-antelope-778957.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Luxury and Cosy',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: ['', 'Tableau de bord administrateur'],
    },
    {
      id: 7,
      title: 'Utopik',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/utopik/utopik.webp',
      screenshots: ['assets/projects/utopik/utopik.webp'],
      demoUrl: 'https://utopik-communication.fr',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Utopik',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 8,
      title: 'Utopik international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/utopikinter/utopikinter.webp',
      screenshots: ['assets/projects/utopikinter/utopikinter.webp'],
      demoUrl: 'https://www.utopik-communication.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Utopik',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 9,
      title: 'Cekterys',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/cekterys/cekterys.webp',
      screenshots: ['assets/projects/cekterys/cekterys.webp'],
      demoUrl: 'https://www.utopik-communication.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Cekterys',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 10,
      title: 'Finky',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/finky/finky.webp',
      screenshots: ['assets/projects/finky/finky.webp'],
      demoUrl: 'https://www.finky-consulting.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Finky',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 11,
      title: 'Inchaate',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/inchaate/inchaate.webp',
      screenshots: ['assets/projects/inchaate/inchaate.webp'],
      demoUrl: 'https://www.inchaate.fr/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Inchaate',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 12,
      title: 'Inchaate international',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/inchaateinter/inchaateinter.webp',
      screenshots: ['assets/projects/inchaateinter/inchaateinter.webp'],
      demoUrl: 'https://inchaate.com',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Inchaate',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 13,
      title: 'Sportneo',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/sportneo/sportneo.webp',
      screenshots: ['assets/projects/sportneo/sportneo.webp'],
      demoUrl: 'https://lightslategray-nightingale-538581.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Sportneo',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
    {
      id: 14,
      title: 'Batrino',
      description: '',
      longDescription: '',
      technologies: ['Next js', 'Node.js', 'MongoDB', 'Tailwind', 'TypeScript'],
      category: 'professionnel',
      image: 'assets/projects/batrino/batrino.webp',
      screenshots: ['assets/projects/batrino/batrino.webp'],
      demoUrl: 'https://www.sienna-squid-376436.hostingersite.com/',
      githubUrl: 'https://github.com/ayarinesrine',
      year: 2024,
      client: 'Batrino',
      duration: '3 mois',
      team: 'Équipe de 4 développeurs',
      challenges: [''],
      features: [''],
    },
  ];

  getProjects(): IProject[] {
    console.log('📦 Tous les projets :', this.projects);
    return this.projects;
  }

  getProjectById(id: number): IProject | undefined {
    console.log('🔍 Recherche du projet avec ID :', id);
    console.log(
      '📋 Projets disponibles :',
      this.projects.map((p) => p.id),
    );
    const project = this.projects.find((p) => p.id === id);
    console.log('✅ Projet trouvé :', project);
    return project;
  }

  getTechnologies(): string[] {
    const techSet = new Set<string>();
    this.projects.forEach((p) => p.technologies.forEach((t) => techSet.add(t)));
    return Array.from(techSet).sort();
  }
}
